<?php

namespace App\DataFixtures;

use App\Entity\Category;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpKernel\KernelInterface;
use App\Service\UploaderService;

use App\Entity\Product;

class ProductFixture extends Fixture
{
    private $kernel;
    private $uploaderService;

    public function __construct(KernelInterface $kernel, UploaderService $uploaderService)

    {
        $this->kernel = $kernel;
        $this->uploaderService = $uploaderService;
    }

    public function load(ObjectManager $manager): void
    {
        //clear uploads directory
        $uploadsDir = $this->kernel->getProjectDir() . '/public/uploads';
        if (is_dir($uploadsDir)) {
            $files = glob($uploadsDir . '/*'); // get all file names
            foreach ($files as $file) { // iterate files
                if (is_file($file)) {
                    unlink($file); // delete file
                }
            }
        }  // Generated by Copilot to be honest


        $this->loadCategories($manager);

        $this->loadProductsOfCategory($manager, "Laptop");
        $this->loadProductsOfCategory($manager, "Computer");
        $this->loadProductsOfCategory($manager, "Monitor");
        $this->loadProductNoCategory($manager, "Mouse");
        $this->loadProductNoCategory($manager, "Keyboard");


    }

    public function loadCategories(ObjectManager $manager): void
    {

        $categories = ["Computer", "Laptop", "Monitor"];
        foreach ($categories as $catName) {
            $category = new Category();
            $category->setName($catName);
            $imageName = "cat_" . strtolower($catName) . '.png';
            $imagePath = $this->kernel->getProjectDir() . "/dummy-data/" . strtolower($catName) . '/' . $imageName;

            $url = $this->uploaderService->copy($imagePath);
            $category->setImageURL($url);
            $manager->persist($category);
        }
        $manager->flush();
    }

    public function loadProductsOfCategory(ObjectManager $manager, string $cat_name): void
    {
        $faker = \Faker\Factory::create();
        $price_min = 100;
        $price_max = 9000;

        for ($i = 0; $i < 6; $i++) {
            $product = new Product();
            $product->setTitle($faker->words(3, true));
            $product->setDescription($faker->words(rand(0, 12), true));
            $product->setPrice(rand($price_min, $price_max));

            $properties = [];
            for ($j = 0; $j < rand(2, 5); $j++) {
                $properties[$faker->word] = rand(1, 100);
            }
            $product->setProperties($properties);

            $category = $manager->getRepository(Category::class)->findOneBy(['name' => $cat_name]);
            if ($category) {
                $product->setCategory($category);
            }


            $image_name = strtolower($cat_name) . '_' . rand(1, 6) . '.png';
            $imagePath = $this->kernel->getProjectDir() . '/dummy-data/' . strtolower($cat_name) . '/' . $image_name;


            if (file_exists($imagePath)) {
                $url = $this->uploaderService->copy($imagePath);
                $product->setImageURL($url);
            }

            $manager->persist($product);
        }

        $manager->flush();

    }

    public function loadProductNoCategory(ObjectManager $manager, string $prod_name): void
    {
        $faker = \Faker\Factory::create();
        $price_min = 100;
        $price_max = 9000;

        for ($i = 0; $i < 5; $i++) {
            $product = new Product();
            $product->setTitle($faker->words(3, true));
            $product->setDescription($faker->words(rand(0, 12), true));
            $product->setPrice(rand($price_min, $price_max));

            $properties = [];
            for ($j = 0; $j < rand(2, 5); $j++) {
                $properties[$faker->word] = rand(1, 100);
            }
            $product->setProperties($properties);


            $image_name = strtolower($prod_name) . '.png';
            $imagePath = $this->kernel->getProjectDir() . '/dummy-data/' . $image_name;


            if (file_exists($imagePath)) {
                $url = $this->uploaderService->copy($imagePath);
                $product->setImageURL($url);
            }

            $manager->persist($product);
        }

        $manager->flush();
    }
    public function getDependencies(): array
    {
        return [CategoryFixtures::class];
    }
}
